//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawNet.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkp_UserInvite_Role
    {
        public System.Guid UserInvite_Role_ID { get; set; }
        public System.Guid UserInvite_ID { get; set; }
        public string AspNetRole_ID { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual tbl_UserInvite tbl_UserInvite { get; set; }
    }
}
