//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawNet.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserInvite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_UserInvite()
        {
            this.lkp_UserInvite_Role = new HashSet<lkp_UserInvite_Role>();
        }
    
        public System.Guid UserInvite_ID { get; set; }
        public string Email { get; set; }
        public System.Guid InviteCode { get; set; }
        public System.DateTime SentDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lkp_UserInvite_Role> lkp_UserInvite_Role { get; set; }
    }
}
